### ISSUE TITLE
Not displaying document becuase of 'X-Frame-Options' set to 'sameorigin'

### ISSUE THREAD

**Issue by esmatullaharifi** [cainsyake/vue-doc-preview#9]
Recently installed the package but after setting up in Vue and loading to view a file, an error occurs

`Refused to display 'https://www.microsoft.com/en-us/microsoft-365/free-office-online-for-the-web?legRedir=true&CorrelationId=cb750c5e-936e-4974-adaf-2800dd576f2c&rtc=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

The component ` <VueDocPreview :value="fileView.url" type="office" />`

**Comment by esmatullaharifi** [comment]
I think the issue is with SSL. Does Microsoft load non-SSL files?

**Comment by cainsyake** [comment]
This package can preview office file because it use iframe to load office file whit microsoft's site. If microsoft's site set 'X-Frame-Options' to 'sameorigin', this package may have some problems. But it is normal in 'https://vdp.cainsyake.com'.
You can refer: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
